#!/usr/bin/python3
import json
import sys
import random

testcase_file = sys.argv[1]
with open(testcase_file) as f:
	testcases = json.load(f)

responses = { }

for (key, testcase) in testcases["testcases"].items():
	time.sleep(0.5 + random.random())
	match testcase["action"]:
		case "add":
			result = { "sum": testcase["a"] + testcase["b"] }

		case "sub":
			result = { "difference": testcase["a"] - testcase["b"] }

		case "mul":
			result = { "product": testcase["a"] * testcase["b"] }

		case _:
			raise Exception(f"Unsupported testcase action: {testcase['action']}")
	responses[key] = result

answer = {
	"responses": responses,
}

print("This comment should be ignored.", file = sys.stderr)
print(json.dumps(answer))
