#!/usr/bin/python3
import json
import sys
import time

testcase_file = sys.argv[1]
with open(testcase_file) as f:
	testcase = json.load(f)

time.sleep(0.5 + random.random())
match testcase["action"]:
	case "add":
		result = { "sum": testcase["a"] + testcase["b"] }

	case "sub":
		result = { "difference": testcase["a"] - testcase["b"] }

	case "mul":
		result = { "product": testcase["a"] * testcase["b"] }

print("This comment should be ignored.", file = sys.stderr)
print(json.dumps(result))
